# Based on gitbucket-pages-plugin:
#   https://github.com/gitbucket/gitbucket-pages-plugin/blob/master/.github/workflows/build.yml
# Which is licensed under the Apache License:
#   https://github.com/gitbucket/gitbucket-pages-plugin/blob/master/LICENSE
#
# Removed test part

name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      env:
        cache-name: cache-sbt-libs
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
          ~/.coursier
        key: build-${{ env.cache-name }}-${{ hashFiles('build.sbt') }}    
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Assembly
      run: sbt assembly
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: gitbucket-chess-plugin-java${{ matrix.java }}-${{ github.sha }}
        path: ./target/scala-2.13/*.jar
